use_frameworks!

target 'HQAMapSwift_Example' do
  pod 'HQAMapSwift', :path => '../'

  target 'HQAMapSwift_Tests' do
    inherit! :search_paths

    
  end
  
  pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
  
end
